/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FluxoTelasController;
import Util.MySQL_POST;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CPD RJ
 */
public class AddMaterialView extends javax.swing.JFrame {

    /**
     * Creates new form AddMaterialView
     */
    public AddMaterialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalvarBt = new javax.swing.JButton();
        CancelarAddBt = new javax.swing.JButton();
        TipoEnviarLb = new javax.swing.JLabel();
        TipoMaterialCb = new javax.swing.JComboBox<>();
        SubTipoCb = new javax.swing.JComboBox<>();
        SubLb = new javax.swing.JLabel();
        AnoMaterialLb = new javax.swing.JLabel();
        AnoTf = new javax.swing.JTextField();
        SemestreCb = new javax.swing.JComboBox<>();
        SemestreLb = new javax.swing.JLabel();
        BaixarLb = new javax.swing.JLabel();
        BaixarTf = new javax.swing.JTextField();
        VisuLb1 = new javax.swing.JLabel();
        VisuTf = new javax.swing.JTextField();
        DisciplinaLb = new javax.swing.JLabel();

        setTitle("Ponto Certo - Adicionar Material");
        setResizable(false);

        SalvarBt.setBackground(new java.awt.Color(255, 255, 255));
        SalvarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        SalvarBt.setToolTipText("Salvar");
        SalvarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalvarBt.setMaximumSize(new java.awt.Dimension(60, 60));
        SalvarBt.setMinimumSize(new java.awt.Dimension(60, 60));
        SalvarBt.setPreferredSize(new java.awt.Dimension(60, 60));
        SalvarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar2.png"))); // NOI18N
        SalvarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBtActionPerformed(evt);
            }
        });

        CancelarAddBt.setBackground(new java.awt.Color(255, 255, 255));
        CancelarAddBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar.png"))); // NOI18N
        CancelarAddBt.setToolTipText("Cancelar");
        CancelarAddBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarAddBt.setMaximumSize(new java.awt.Dimension(60, 60));
        CancelarAddBt.setMinimumSize(new java.awt.Dimension(60, 60));
        CancelarAddBt.setPreferredSize(new java.awt.Dimension(60, 60));
        CancelarAddBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar2.png"))); // NOI18N
        CancelarAddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarAddBtActionPerformed(evt);
            }
        });

        TipoEnviarLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        TipoEnviarLb.setText("Tipo:");

        TipoMaterialCb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        TipoMaterialCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prova", "Trabalho", "Projeto", "Lista" }));
        TipoMaterialCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoMaterialCbActionPerformed(evt);
            }
        });

        SubTipoCb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        SubTipoCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "Reposição" }));
        SubTipoCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTipoCbActionPerformed(evt);
            }
        });

        SubLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        SubLb.setText("Sub-Tipo:");

        AnoMaterialLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        AnoMaterialLb.setText("Ano:");

        AnoTf.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N

        SemestreCb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        SemestreCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        SemestreCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemestreCbActionPerformed(evt);
            }
        });

        SemestreLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        SemestreLb.setText("Semestre:");

        BaixarLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        BaixarLb.setText("URL Baixar:");

        VisuLb1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        VisuLb1.setText("URLVisualizar:");

        DisciplinaLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        DisciplinaLb.setText("\"X\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SalvarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CancelarAddBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TipoMaterialCb, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TipoEnviarLb)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AnoMaterialLb)
                                        .addComponent(AnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SemestreLb)
                                        .addComponent(SemestreCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SubLb)
                                .addComponent(SubTipoCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(BaixarLb)
                        .addComponent(BaixarTf)
                        .addComponent(VisuLb1)
                        .addComponent(VisuTf))
                    .addComponent(DisciplinaLb))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DisciplinaLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoEnviarLb)
                    .addComponent(SubLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoMaterialCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTipoCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnoMaterialLb)
                    .addComponent(SemestreLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SemestreCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BaixarLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BaixarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VisuLb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisuTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalvarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarAddBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBtActionPerformed
        if ( AnoTf.getText().trim().equals("")||BaixarTf.getText().trim().equals("")||VisuTf.getText().trim().equals("") )
           JOptionPane.showMessageDialog(null, "Por favor insira todos os dados.", "Erro", JOptionPane.ERROR_MESSAGE, new ImageIcon ("src/Imagens/Aviso.png"));
       else{        
           
            
            String DISCIPLINA_NOME = DisciplinaLb.getText().trim();
            String SEMESTRE = AnoTf.getText()+"-"+SemestreCb.getSelectedItem();
            String TIPO = TipoMaterialCb.getSelectedItem().toString()+SubTipoCb.getSelectedItem().toString();
            String URL = BaixarTf.getText();
            String VALUES = "'"+DISCIPLINA_NOME+"','"+SEMESTRE+"','"+TIPO+"','"+URL+"'";
            MySQL_POST.main("INSERT INTO MATERIAL (DISCIPLINA_NOME,SEMESTRE,TIPO,URL) VALUES("+VALUES+");");
            
            
           Reseta();
           JOptionPane.showMessageDialog(null, "Material adicionado com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE, new ImageIcon ("src/Imagens/Ok.png"));
           
           FluxoTelasController.getCdv().setVisible(true);
           this.setVisible(false);
       }
    }//GEN-LAST:event_SalvarBtActionPerformed

    private void CancelarAddBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarAddBtActionPerformed
        Reseta();
        FluxoTelasController.getCdv().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelarAddBtActionPerformed

    private void TipoMaterialCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoMaterialCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoMaterialCbActionPerformed

    private void SubTipoCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTipoCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubTipoCbActionPerformed

    private void SemestreCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemestreCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemestreCbActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Reseta(){
        TipoMaterialCb.setSelectedItem(0);
        SubTipoCb.setSelectedIndex(0);
        AnoTf.setText("");
        SemestreCb.setSelectedIndex(0);
        BaixarTf.setText("");
        VisuTf.setText("");
    }
    
    public void setNomeDisciplinaLb(String text)
    {
        DisciplinaLb.setText(text);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMaterialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMaterialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMaterialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMaterialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMaterialView().setVisible(true);
            }
        });
    }    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnoMaterialLb;
    private javax.swing.JTextField AnoTf;
    private javax.swing.JLabel BaixarLb;
    private javax.swing.JTextField BaixarTf;
    private javax.swing.JButton CancelarAddBt;
    private javax.swing.JLabel DisciplinaLb;
    private javax.swing.JButton SalvarBt;
    private javax.swing.JComboBox<String> SemestreCb;
    private javax.swing.JLabel SemestreLb;
    private javax.swing.JLabel SubLb;
    private javax.swing.JComboBox<String> SubTipoCb;
    private javax.swing.JLabel TipoEnviarLb;
    private javax.swing.JComboBox<String> TipoMaterialCb;
    private javax.swing.JLabel VisuLb1;
    private javax.swing.JTextField VisuTf;
    // End of variables declaration//GEN-END:variables
}
