/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FluxoTelasController;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import mvcpontocerto.hiperlink;

/**
 *
 * @author labccet
 */
public class DisciplinaView extends javax.swing.JFrame {

    /**
     * Creates new form ControleDisciplinaView
     */
    public DisciplinaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisciplinaLb = new javax.swing.JLabel();
        VoltarBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MaterialLt = new javax.swing.JList<>();
        VisualizarBt = new javax.swing.JButton();
        BaixarBt = new javax.swing.JButton();
        DenunciarBt = new javax.swing.JButton();
        DisciplinaLb1 = new javax.swing.JLabel();

        DisciplinaLb.setText("\" X\"");
        DisciplinaLb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        VoltarBt.setText("Voltar");
        VoltarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtActionPerformed(evt);
            }
        });

        MaterialLt.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Prova2 2016.1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(MaterialLt);

        VisualizarBt.setText("Visualizar");
        VisualizarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisualizarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarBtActionPerformed(evt);
            }
        });

        BaixarBt.setText("Baixar");
        BaixarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        DenunciarBt.setText("Denunciar");
        DenunciarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DenunciarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenunciarBtActionPerformed(evt);
            }
        });

        DisciplinaLb1.setText("\" X\"");
        DisciplinaLb1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VoltarBt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DenunciarBt, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(VisualizarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BaixarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(DisciplinaLb1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VoltarBt)
                .addGap(20, 20, 20)
                .addComponent(DisciplinaLb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(VisualizarBt)
                        .addGap(18, 18, 18)
                        .addComponent(BaixarBt)
                        .addGap(18, 18, 18)
                        .addComponent(DenunciarBt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtActionPerformed
        //new FavoritosView().show();
        FluxoTelasController.cfv.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarBtActionPerformed

    private void VisualizarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarBtActionPerformed
        // TODO add your handling code here:
        
        hiperlink hp = new hiperlink();
        
        try {
            hp.open(new URI(MaterialLt.getModel().getElementAt(0)));
        } catch (URISyntaxException ex) {
            Logger.getLogger(DisciplinaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_VisualizarBtActionPerformed

    private void DenunciarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenunciarBtActionPerformed
        new DenunciarView().show();
        dispose();
    }//GEN-LAST:event_DenunciarBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisciplinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisciplinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisciplinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisciplinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisciplinaView().setVisible(true);
            }
        });
    }
    
    public void setNomeDisciplina(String nome)
    {
        DisciplinaLb1.setText(nome);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BaixarBt;
    private javax.swing.JButton DenunciarBt;
    private javax.swing.JLabel DisciplinaLb;
    private javax.swing.JLabel DisciplinaLb1;
    private javax.swing.JList<String> MaterialLt;
    private javax.swing.JButton VisualizarBt;
    private javax.swing.JButton VoltarBt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
