/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FluxoTelasController;
import Util.Download;
import Util.MySQL_POST;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import Util.hiperlink;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author labccet
 */
public class MateriaisView extends javax.swing.JFrame {

    /**
     * Creates new form ControleDisciplinaView
     */
    public MateriaisView() {
        initComponents();
    }
    
     public void carregaMaterial()
    {
        //System.out.println("SELECT COUNT(1) FROM MATERIAL WHERE DISCIPLINA_NOME = '"+ DisciplinaLb1.getText().trim()+"'");
        String c = (String) MySQL_POST.carregaListaDisc("SELECT COUNT(1) FROM MATERIAL WHERE DISCIPLINA_NOME = '"+ DisciplinaLb1.getText().trim()+"'").get(0);

        int count = Integer.parseInt(c.replace("	", ""));
        
        DefaultTableModel dtm= new DefaultTableModel();
        dtm = (DefaultTableModel) materialTb.getModel();
        
        if(count>dtm.getRowCount())
        {
            dtm.setRowCount(count);
        }
        
        ArrayList<String> semestres = MySQL_POST.carregaListaDisc("SELECT SEMESTRE FROM MATERIAL WHERE DISCIPLINA_NOME = '"+DisciplinaLb1.getText().trim()+"' ORDER BY SEMESTRE DESC");
        //System.out.println("SELECT SEMESTRE FROM MATERIAL WHERE DISCIPLINA_NOME = '"+DisciplinaLb1.getText().trim()+"' ORDER BY SEMESTRE DESC");
        ArrayList<String> tipo = MySQL_POST.carregaListaDisc("SELECT TIPO FROM MATERIAL WHERE DISCIPLINA_NOME = '"+DisciplinaLb1.getText().trim()+"' ORDER BY SEMESTRE DESC");
        ArrayList<String> url = MySQL_POST.carregaListaDisc("SELECT URL FROM MATERIAL WHERE DISCIPLINA_NOME = '"+DisciplinaLb1.getText().trim()+"' ORDER BY SEMESTRE DESC");
        
        for(int i = 0; i< count ;i++)
        {
            dtm.setValueAt(semestres.get(i), i, 0);
            dtm.setValueAt(tipo.get(i), i, 1);
            dtm.setValueAt(url.get(i), i, 2);
        }
        
        materialTb.setModel(dtm);
//        lt = MySQL_POST.carregaListaDiscModel("select URL from ENDERECO where NOME_DISCIPLINA = '"+ DisciplinaLb1.getText().trim() + "'");
//            System.out.println("select URL from ENDERECO where NOME_DISCIPLINA = '"+ DisciplinaLb1.getText().trim() + "'");
            //System.out.println(DisciplinaLb1.getText());
            //System.out.println(MySQL_POST.carregaListaDiscModel("select url from ENDERECO where NOME_DISCIPLINA = "+ DisciplinaLb1.getText()));
        
        //MaterialLt.setModel(lt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisciplinaLb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        VoltarBt = new javax.swing.JButton();
        VisualizarBt = new javax.swing.JButton();
        DenunciarBt = new javax.swing.JButton();
        DisciplinaLb1 = new javax.swing.JLabel();
        AddBt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        materialTb = new javax.swing.JTable();
        RemBt = new javax.swing.JButton();

        DisciplinaLb.setText("\" X\"");
        DisciplinaLb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto Certo - Materiais");
        setLocationByPlatform(true);
        setResizable(false);

        VoltarBt.setBackground(new java.awt.Color(255, 255, 255));
        VoltarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarBt.setToolTipText("Voltar");
        VoltarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBt.setMaximumSize(new java.awt.Dimension(36, 36));
        VoltarBt.setMinimumSize(new java.awt.Dimension(36, 36));
        VoltarBt.setPreferredSize(new java.awt.Dimension(36, 36));
        VoltarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar2.png"))); // NOI18N
        VoltarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtActionPerformed(evt);
            }
        });

        VisualizarBt.setBackground(new java.awt.Color(255, 255, 255));
        VisualizarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Visualizar.png"))); // NOI18N
        VisualizarBt.setToolTipText("Visualizar");
        VisualizarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisualizarBt.setMaximumSize(new java.awt.Dimension(60, 60));
        VisualizarBt.setMinimumSize(new java.awt.Dimension(60, 60));
        VisualizarBt.setPreferredSize(new java.awt.Dimension(60, 60));
        VisualizarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Visualizar2.png"))); // NOI18N
        VisualizarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarBtActionPerformed(evt);
            }
        });

        DenunciarBt.setBackground(new java.awt.Color(255, 255, 255));
        DenunciarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Denunciar.png"))); // NOI18N
        DenunciarBt.setToolTipText("Denunciar");
        DenunciarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DenunciarBt.setMaximumSize(new java.awt.Dimension(60, 60));
        DenunciarBt.setMinimumSize(new java.awt.Dimension(60, 60));
        DenunciarBt.setPreferredSize(new java.awt.Dimension(60, 60));
        DenunciarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Denunciar2.png"))); // NOI18N
        DenunciarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenunciarBtActionPerformed(evt);
            }
        });

        DisciplinaLb1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        DisciplinaLb1.setText("\" X\"");
        DisciplinaLb1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        AddBt.setBackground(new java.awt.Color(255, 255, 255));
        AddBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Adicionaradm.png"))); // NOI18N
        AddBt.setToolTipText("Adicionar Material");
        AddBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBt.setEnabled(false);
        AddBt.setMaximumSize(new java.awt.Dimension(60, 60));
        AddBt.setMinimumSize(new java.awt.Dimension(60, 60));
        AddBt.setPreferredSize(new java.awt.Dimension(60, 60));
        AddBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Adicionaradm2.png"))); // NOI18N
        AddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtActionPerformed(evt);
            }
        });

        materialTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semestre", "Tipo", "URL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        materialTb.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(materialTb);

        RemBt.setBackground(new java.awt.Color(255, 255, 255));
        RemBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Rem.png"))); // NOI18N
        RemBt.setToolTipText("Remover Material");
        RemBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RemBt.setEnabled(false);
        RemBt.setMaximumSize(new java.awt.Dimension(60, 60));
        RemBt.setMinimumSize(new java.awt.Dimension(60, 60));
        RemBt.setPreferredSize(new java.awt.Dimension(60, 60));
        RemBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Rem2.png"))); // NOI18N
        RemBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VoltarBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisciplinaLb1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(VisualizarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DenunciarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RemBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VoltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(DisciplinaLb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DenunciarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisualizarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtActionPerformed
        //new FavoritosView().show();
        FluxoTelasController.getCfv().setVisible(true);
        this.setVisible(false);
        ((DefaultTableModel)materialTb.getModel()).setRowCount(0);
    }//GEN-LAST:event_VoltarBtActionPerformed

    private void VisualizarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarBtActionPerformed
        // TODO add your handling code here:
        if(materialTb.getSelectedRow() == -1 )
        {
            JOptionPane.showMessageDialog(null, "Por favor selecione uma material.", "Erro", JOptionPane.ERROR_MESSAGE, new ImageIcon ("src/Imagens/Aviso.png"));
        }
        else{
            hiperlink hp = new hiperlink();
        
            try {
                hp.open(new URI( materialTb.getValueAt(materialTb.getSelectedRow(), 2).toString().trim()));
            } catch (URISyntaxException ex) {
                Logger.getLogger(MateriaisView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_VisualizarBtActionPerformed

    private void DenunciarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenunciarBtActionPerformed
         if(materialTb.getSelectedRow() == -1 )
        {
            JOptionPane.showMessageDialog(null, "Por favor selecione uma material.", "Erro", JOptionPane.ERROR_MESSAGE, new ImageIcon ("src/Imagens/Aviso.png"));
        }
        else{
            this.setEnabled(false);
            FluxoTelasController.getDv().setVisible(true);
         }
    }//GEN-LAST:event_DenunciarBtActionPerformed

    private void AddBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtActionPerformed
        this.setEnabled(false);
        FluxoTelasController.getAmv().setVisible(true); 
        FluxoTelasController.getAmv().setNomeDisciplinaLb(DisciplinaLb1.getText());
    }//GEN-LAST:event_AddBtActionPerformed

    private void RemBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemBtActionPerformed
        int Remove = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deslogar?", "Aviso", JOptionPane.YES_NO_OPTION, 0, new ImageIcon ("src/Imagens/Pergunta.png"));  
        
        if(Remove != 1){
            //remove
        }
    }//GEN-LAST:event_RemBtActionPerformed

    public JButton getAddBt(){
        return AddBt;
    }
    
    public JButton getRemBt(){
        return RemBt;
    }
    
    public String getTipo(){
        return (String) materialTb.getValueAt(materialTb.getSelectedRow(), 1);
    }
    
    public String getSemestre(){
        return (String) materialTb.getValueAt(materialTb.getSelectedRow(), 0);
    }
    
    public String getDisciplina(){
        return DisciplinaLb1.getText();
    }    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MateriaisView().setVisible(true);
            }
        });
    }
    
    public void setNomeDisciplina(String nome)
    {
        DisciplinaLb1.setText(nome);
    }    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBt;
    private javax.swing.JButton DenunciarBt;
    private javax.swing.JLabel DisciplinaLb;
    private javax.swing.JLabel DisciplinaLb1;
    private javax.swing.JButton RemBt;
    private javax.swing.JButton VisualizarBt;
    private javax.swing.JButton VoltarBt;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable materialTb;
    // End of variables declaration//GEN-END:variables
}
