/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FluxoTelasController;
import Util.MySQL_POST;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import Util.hiperlink;
import javax.swing.DefaultListModel;
import javax.swing.JButton;

/**
 *
 * @author labccet
 */
public class MateriaisView extends javax.swing.JFrame {

    /**
     * Creates new form ControleDisciplinaView
     */
    public MateriaisView() {
        initComponents();
    }
    
     public void carregaMaterial()
    {
        DefaultListModel<String> lt = new DefaultListModel<>();
        
        lt = MySQL_POST.carregaListaDiscModel("select URL from ENDERECO where NOME_DISCIPLINA = '"+ DisciplinaLb1.getText().trim() + "'");
            System.out.println("select URL from ENDERECO where NOME_DISCIPLINA = '"+ DisciplinaLb1.getText().trim() + "'");
            //System.out.println(DisciplinaLb1.getText());
            //System.out.println(MySQL_POST.carregaListaDiscModel("select url from ENDERECO where NOME_DISCIPLINA = "+ DisciplinaLb1.getText()));
        
        MaterialLt.setModel(lt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisciplinaLb = new javax.swing.JLabel();
        VoltarBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MaterialLt = new javax.swing.JList<>();
        VisualizarBt = new javax.swing.JButton();
        BaixarBt = new javax.swing.JButton();
        DenunciarBt = new javax.swing.JButton();
        DisciplinaLb1 = new javax.swing.JLabel();
        AddBt = new javax.swing.JButton();

        DisciplinaLb.setText("\" X\"");
        DisciplinaLb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto Certo - Materiais");
        setLocationByPlatform(true);
        setResizable(false);

        VoltarBt.setBackground(new java.awt.Color(255, 255, 255));
        VoltarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarBt.setToolTipText("Voltar");
        VoltarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBt.setMaximumSize(new java.awt.Dimension(36, 36));
        VoltarBt.setMinimumSize(new java.awt.Dimension(36, 36));
        VoltarBt.setPreferredSize(new java.awt.Dimension(36, 36));
        VoltarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar2.png"))); // NOI18N
        VoltarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtActionPerformed(evt);
            }
        });

        MaterialLt.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        MaterialLt.setToolTipText("");
        MaterialLt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(MaterialLt);

        VisualizarBt.setBackground(new java.awt.Color(255, 255, 255));
        VisualizarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Visualizar.png"))); // NOI18N
        VisualizarBt.setToolTipText("Visualizar");
        VisualizarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisualizarBt.setMaximumSize(new java.awt.Dimension(60, 60));
        VisualizarBt.setMinimumSize(new java.awt.Dimension(60, 60));
        VisualizarBt.setPreferredSize(new java.awt.Dimension(60, 60));
        VisualizarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Visualizar2.png"))); // NOI18N
        VisualizarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarBtActionPerformed(evt);
            }
        });

        BaixarBt.setBackground(new java.awt.Color(255, 255, 255));
        BaixarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Baixar.png"))); // NOI18N
        BaixarBt.setToolTipText("Baixar");
        BaixarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BaixarBt.setMaximumSize(new java.awt.Dimension(60, 60));
        BaixarBt.setMinimumSize(new java.awt.Dimension(60, 60));
        BaixarBt.setPreferredSize(new java.awt.Dimension(60, 60));
        BaixarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Baixar2.png"))); // NOI18N
        BaixarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaixarBtActionPerformed(evt);
            }
        });

        DenunciarBt.setBackground(new java.awt.Color(255, 255, 255));
        DenunciarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Denunciar.png"))); // NOI18N
        DenunciarBt.setToolTipText("Denunciar");
        DenunciarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DenunciarBt.setMaximumSize(new java.awt.Dimension(60, 60));
        DenunciarBt.setMinimumSize(new java.awt.Dimension(60, 60));
        DenunciarBt.setPreferredSize(new java.awt.Dimension(60, 60));
        DenunciarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Denunciar2.png"))); // NOI18N
        DenunciarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenunciarBtActionPerformed(evt);
            }
        });

        DisciplinaLb1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        DisciplinaLb1.setText("\" X\"");
        DisciplinaLb1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        AddBt.setBackground(new java.awt.Color(255, 255, 255));
        AddBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Adicionaradm.png"))); // NOI18N
        AddBt.setToolTipText("Adicionar Material");
        AddBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBt.setEnabled(false);
        AddBt.setMaximumSize(new java.awt.Dimension(60, 60));
        AddBt.setMinimumSize(new java.awt.Dimension(60, 60));
        AddBt.setPreferredSize(new java.awt.Dimension(60, 60));
        AddBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Adicionaradm2.png"))); // NOI18N
        AddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VoltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisciplinaLb1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VisualizarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DenunciarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BaixarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VoltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(DisciplinaLb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DenunciarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BaixarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisualizarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtActionPerformed
        //new FavoritosView().show();
        FluxoTelasController.getCfv().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarBtActionPerformed

    private void VisualizarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarBtActionPerformed
        // TODO add your handling code here:
        
        hiperlink hp = new hiperlink();
        
        try {
            hp.open(new URI(MaterialLt.getModel().getElementAt(0)));
        } catch (URISyntaxException ex) {
            Logger.getLogger(MateriaisView.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_VisualizarBtActionPerformed

    private void DenunciarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenunciarBtActionPerformed
        FluxoTelasController.getDv().setVisible(true);        
    }//GEN-LAST:event_DenunciarBtActionPerformed

    private void BaixarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaixarBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaixarBtActionPerformed

    private void AddBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtActionPerformed
        FluxoTelasController.getAmv().setVisible(true);         
    }//GEN-LAST:event_AddBtActionPerformed

    public JButton getAddBt(){
        return AddBt;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MateriaisView().setVisible(true);
            }
        });
    }
    
    public void setNomeDisciplina(String nome)
    {
        DisciplinaLb1.setText(nome);
    }    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBt;
    private javax.swing.JButton BaixarBt;
    private javax.swing.JButton DenunciarBt;
    private javax.swing.JLabel DisciplinaLb;
    private javax.swing.JLabel DisciplinaLb1;
    private javax.swing.JList<String> MaterialLt;
    private javax.swing.JButton VisualizarBt;
    private javax.swing.JButton VoltarBt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
