/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import Model.NotaModel;
import Util.doSomethingOnClose;
import View.FavoritosView;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public class NotaView extends javax.swing.JFrame {       
    /**
     * Creates new form ControleDisciplinaView
     */
    DisciplinasController2 dc;
    DefaultTableModel defaultTableModel;
    public NotaView() {
        initComponents();
        dc = FluxoTelasController.getDc2();  
        defaultTableModel = (DefaultTableModel) NotasTb.getModel();
        doSomethingOnClose.newWindowEvent(this);
    }
    
    public void calculaMedia()
    {
        calculaNotaReal();
        double somaNotaReal = 0;
        double somaPesos = 0;
        String media;
        
        for(int i = 0; i< NotasTb.getRowCount();i++)
        {
            somaPesos = somaPesos + (double)NotasTb.getValueAt(i, 2);
            somaNotaReal = somaNotaReal + (double)NotasTb.getValueAt(i, 3);            
        }
        
        media = format(somaNotaReal/somaPesos);
        ValorLb.setText(media);
    }
    
    public void calculaNotaReal()
    {
        double nota = 0;
        double peso = 0;
        //double notareal;
        
       for(int i = 0; i< NotasTb.getRowCount();i++)
        {           
            nota = (double)NotasTb.getValueAt(i, 1);
            peso = (double)NotasTb.getValueAt(i, 2);
            
            NotasTb.setValueAt(nota*peso, i, 3);
        } 
    }

    public void carregaNotaDisc()
    {
       //NotasTb.setModel(defaultTableModel);
        
//        for(int i = 0; i< NotasTb.getRowCount();i++)
//        {
//            for(int j = 0; j<NotasTb.getColumnCount();j++)
//            {
//                NotasTb.setValueAt(null, i, j);
//            }
//        }
       
       int nNotas = dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().size();
       
       //System.out.println("tamanho:"+ dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().size());
       double aNota;
       String aTipo;
       double aPeso;
       
        DefaultTableModel dtmAdd = new DefaultTableModel();
        dtmAdd = (DefaultTableModel) NotasTb.getModel();
        dtmAdd.setRowCount(nNotas);
        NotasTb.setModel(dtmAdd); 
       
       for(int i = 0; i < nNotas; i++)
       {
           aTipo = dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).getTipo();
           aNota = dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).getNota();
           aPeso = dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).getPeso();           
           NotasTb.setValueAt(aTipo, i, 0);
           NotasTb.setValueAt(aNota, i, 1);
           NotasTb.setValueAt(aPeso, i, 2);
       }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DisciplinaLb = new javax.swing.JLabel();
        VoltarBt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NotasTb = new javax.swing.JTable();
        SalvarNotaBt = new javax.swing.JButton();
        ExcluirNotaBt = new javax.swing.JButton();
        NovaNotaBt = new javax.swing.JButton();
        MediaLb = new javax.swing.JLabel();
        ValorLb = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto Certo - Notas");

        DisciplinaLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        DisciplinaLb.setText("\" X\"");
        DisciplinaLb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        VoltarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarBt.setToolTipText("Voltar");
        VoltarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBt.setMaximumSize(new java.awt.Dimension(36, 36));
        VoltarBt.setMinimumSize(new java.awt.Dimension(36, 36));
        VoltarBt.setPreferredSize(new java.awt.Dimension(36, 36));
        VoltarBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar2.png"))); // NOI18N
        VoltarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtActionPerformed(evt);
            }
        });

        NotasTb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        NotasTb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        NotasTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Nota", "Peso", "Nota Real"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(NotasTb);

        SalvarNotaBt.setBackground(new java.awt.Color(255, 255, 255));
        SalvarNotaBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        SalvarNotaBt.setToolTipText("Salvar");
        SalvarNotaBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalvarNotaBt.setMaximumSize(new java.awt.Dimension(60, 60));
        SalvarNotaBt.setMinimumSize(new java.awt.Dimension(60, 60));
        SalvarNotaBt.setPreferredSize(new java.awt.Dimension(60, 60));
        SalvarNotaBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar2.png"))); // NOI18N
        SalvarNotaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarNotaBtActionPerformed(evt);
            }
        });

        ExcluirNotaBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        ExcluirNotaBt.setToolTipText("Excluir");
        ExcluirNotaBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExcluirNotaBt.setMaximumSize(new java.awt.Dimension(60, 60));
        ExcluirNotaBt.setMinimumSize(new java.awt.Dimension(60, 60));
        ExcluirNotaBt.setPreferredSize(new java.awt.Dimension(60, 60));
        ExcluirNotaBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir2.png"))); // NOI18N
        ExcluirNotaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirNotaBtActionPerformed(evt);
            }
        });

        NovaNotaBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Nova.png"))); // NOI18N
        NovaNotaBt.setToolTipText("Nova");
        NovaNotaBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NovaNotaBt.setMaximumSize(new java.awt.Dimension(60, 60));
        NovaNotaBt.setMinimumSize(new java.awt.Dimension(60, 60));
        NovaNotaBt.setPreferredSize(new java.awt.Dimension(60, 60));
        NovaNotaBt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Nova2.png"))); // NOI18N
        NovaNotaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaNotaBtActionPerformed(evt);
            }
        });

        MediaLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        MediaLb.setText("Média:");

        ValorLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        ValorLb.setText("0.0");
        ValorLb.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SalvarNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NovaNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VoltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisciplinaLb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValorLb)
                            .addComponent(MediaLb))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VoltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MediaLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorLb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisciplinaLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalvarNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NovaNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtActionPerformed
        //new FavoritosView().show();
        FluxoTelasController.getCfv().setVisible(true);
        dispose();
        //this.setVisible(false);
    }//GEN-LAST:event_VoltarBtActionPerformed

    private void NovaNotaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaNotaBtActionPerformed

        DefaultTableModel dtmAdd = new DefaultTableModel();

        dtmAdd = (DefaultTableModel) NotasTb.getModel();
        dtmAdd.setRowCount(dtmAdd.getRowCount()+1);
        NotasTb.setModel(dtmAdd); 
    }//GEN-LAST:event_NovaNotaBtActionPerformed

    private void SalvarNotaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarNotaBtActionPerformed
//        NotasTb.selectAll();   
//        int line = NotasTb.getSelectedRow();     
//        
//        double media = nt.CalculaNotaPeso((double) NotasTb.getModel().getValueAt(line, 1), (double)NotasTb.getModel().getValueAt(line, 2));
//        NotasTb.setValueAt(media, line, 3); 
//        
//        NotasTb.setEditingRow(line);
//        
//        DisciplinasController2 dc = FluxoTelasController.getCfv().getDisciplinaController2();
//        
//        dc.getDisciplinas();
//       int nNotas = NotasTb.getModel().getRowCount();
//       double aNota;
//       String aTipo;
//       double aPeso;       
  
        
        
       int nNotas = NotasTb.getModel().getRowCount();
       double aNota;
       String aTipo;
       double aPeso;       
       
       
       try{
//       if(dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().size()<nNotas)
//       {
//           for(int i = 0; i < (nNotas - dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().size());i++)
//           {
//               dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().add(new NotaModel());
//           }
//       }
            dc.getDisciplinasEspecifica(DisciplinaLb.getText()).deletaNotas();
            
            for(int i = 0; i < nNotas; i++)
           {
               dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().add(new NotaModel());
           }
       

            //System.out.println(NotasTb.getValueAt(0,2));
       for(int i = 0; i < nNotas; i++)
       {
                     
           aTipo = (String) NotasTb.getValueAt(i, 0);
           aNota =  (double) NotasTb.getValueAt(i, 1);
           aPeso =  (double) NotasTb.getValueAt(i, 2);

           
           
           dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).setTipo(aTipo);
           dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).setNota(aNota);
           dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).setPeso(aPeso);           
       }
       
       
       dc.serializaDisciplinas();     
       calculaMedia();
       }
       catch(Exception e){           
           JOptionPane.showMessageDialog(null, "Por favor desecelecione a coluna e tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE, new ImageIcon ("src/Imagens/Aviso.png"));
       }
        
    }//GEN-LAST:event_SalvarNotaBtActionPerformed

    private void ExcluirNotaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirNotaBtActionPerformed
        ((DefaultTableModel)NotasTb.getModel()).removeRow(NotasTb.getSelectedRow());
    }//GEN-LAST:event_ExcluirNotaBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaView().setVisible(true);
            }
        });
    }
    
    public void setNomeDisciplina(String nome)
    {
        DisciplinaLb.setText(nome);
    }
    private static String format(double x) {
        if(x == 10)
            return String.format("%.1f", x); 
        else
            return String.format("%.2f", x);  
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisciplinaLb;
    private javax.swing.JButton ExcluirNotaBt;
    private javax.swing.JLabel MediaLb;
    private javax.swing.JTable NotasTb;
    private javax.swing.JButton NovaNotaBt;
    private javax.swing.JButton SalvarNotaBt;
    private javax.swing.JLabel ValorLb;
    private javax.swing.JButton VoltarBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
