/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import Model.NotaModel;
import View.FavoritosView;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public class NotaView extends javax.swing.JFrame {       
    /**
     * Creates new form ControleDisciplinaView
     */
    DisciplinasController2 dc;
    DefaultTableModel defaultTableModel;
    public NotaView() {
        initComponents();
        dc = FluxoTelasController.getDc2();  
        defaultTableModel = (DefaultTableModel) NotasTb.getModel();
    }

    public void carregaNotaDisc()
    {
       //NotasTb.setModel(defaultTableModel);
       
       int nNotas = dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().size();
       //System.out.println("tamanho:"+ dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().size());
       double aNota;
       String aTipo;
       double aPeso;
       
        DefaultTableModel dtmAdd = new DefaultTableModel();
        dtmAdd = (DefaultTableModel) NotasTb.getModel();
        dtmAdd.setRowCount(nNotas);
        NotasTb.setModel(dtmAdd); 
       
       for(int i = 0; i < nNotas; i++)
       {
           aTipo = dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).getTipo();
           aNota = dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).getNota();
           aPeso = dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).getPeso();           
           NotasTb.setValueAt(aTipo, i, 1);
           NotasTb.setValueAt(aNota, i, 2);
           NotasTb.setValueAt(aPeso, i, 3);
       }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DisciplinaLb = new javax.swing.JLabel();
        VoltarBt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NotasTb = new javax.swing.JTable();
        SalvarNotaBt = new javax.swing.JButton();
        ExcluirNotaBt = new javax.swing.JButton();
        EditarNotaBt = new javax.swing.JButton();
        NovaNotaBt = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto Certo");

        DisciplinaLb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        DisciplinaLb.setText("\" X\"");
        DisciplinaLb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        VoltarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        VoltarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBt.setMaximumSize(new java.awt.Dimension(36, 36));
        VoltarBt.setMinimumSize(new java.awt.Dimension(36, 36));
        VoltarBt.setPreferredSize(new java.awt.Dimension(36, 36));
        VoltarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtActionPerformed(evt);
            }
        });

        NotasTb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        NotasTb.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        NotasTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Nota", "Peso", "Nota Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(NotasTb);

        SalvarNotaBt.setBackground(new java.awt.Color(255, 255, 255));
        SalvarNotaBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        SalvarNotaBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalvarNotaBt.setMaximumSize(new java.awt.Dimension(60, 60));
        SalvarNotaBt.setMinimumSize(new java.awt.Dimension(60, 60));
        SalvarNotaBt.setPreferredSize(new java.awt.Dimension(60, 60));
        SalvarNotaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarNotaBtActionPerformed(evt);
            }
        });

        ExcluirNotaBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        ExcluirNotaBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExcluirNotaBt.setMaximumSize(new java.awt.Dimension(60, 60));
        ExcluirNotaBt.setMinimumSize(new java.awt.Dimension(60, 60));
        ExcluirNotaBt.setPreferredSize(new java.awt.Dimension(60, 60));
        ExcluirNotaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirNotaBtActionPerformed(evt);
            }
        });

        EditarNotaBt.setBackground(new java.awt.Color(255, 255, 255));
        EditarNotaBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Editar.png"))); // NOI18N
        EditarNotaBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarNotaBt.setMaximumSize(new java.awt.Dimension(60, 60));
        EditarNotaBt.setMinimumSize(new java.awt.Dimension(60, 60));
        EditarNotaBt.setPreferredSize(new java.awt.Dimension(60, 60));
        EditarNotaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarNotaBtActionPerformed(evt);
            }
        });

        NovaNotaBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Nova.png"))); // NOI18N
        NovaNotaBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NovaNotaBt.setMaximumSize(new java.awt.Dimension(60, 60));
        NovaNotaBt.setMinimumSize(new java.awt.Dimension(60, 60));
        NovaNotaBt.setPreferredSize(new java.awt.Dimension(60, 60));
        NovaNotaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaNotaBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SalvarNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditarNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ExcluirNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NovaNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DisciplinaLb)
                            .addComponent(VoltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VoltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(DisciplinaLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalvarNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NovaNotaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtActionPerformed
        //new FavoritosView().show();
        FluxoTelasController.getCfv().setVisible(true);
        dispose();
        //this.setVisible(false);
    }//GEN-LAST:event_VoltarBtActionPerformed

    private void NovaNotaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaNotaBtActionPerformed

        DefaultTableModel dtmAdd = new DefaultTableModel();

        dtmAdd = (DefaultTableModel) NotasTb.getModel();
        dtmAdd.setRowCount(dtmAdd.getRowCount()+1);
        NotasTb.setModel(dtmAdd); 
    }//GEN-LAST:event_NovaNotaBtActionPerformed

    private void SalvarNotaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarNotaBtActionPerformed
//        NotasTb.selectAll();   
//        int line = NotasTb.getSelectedRow();     
//        
//        double media = nt.CalculaNotaPeso((double) NotasTb.getModel().getValueAt(line, 1), (double)NotasTb.getModel().getValueAt(line, 2));
//        NotasTb.setValueAt(media, line, 3); 
//        
//        NotasTb.setEditingRow(line);
//        
//        DisciplinasController2 dc = FluxoTelasController.getCfv().getDisciplinaController2();
//        
//        dc.getDisciplinas();

       int nNotas = NotasTb.getModel().getRowCount();
       double aNota;
       String aTipo;
       double aPeso;
       
       if(dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().size()<nNotas)
       {
           for(int i = 0; i < (nNotas - dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().size());i++)
           {
               dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().add(new NotaModel());
           }
       }
       System.out.println(NotasTb.getValueAt(0,2));
       for(int i = 0; i < nNotas; i++)
       {
           aTipo = (String) NotasTb.getValueAt(i, 0);
           aNota =  (double) NotasTb.getValueAt(i, 1);
           aPeso =  (double) NotasTb.getValueAt(i, 2);           
           
           dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).setTipo(aTipo);
           dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).setNota(aNota);
           dc.getDisciplinasEspecifica(DisciplinaLb.getText()).getNotas().get(i).setPeso(aPeso);           
       }
                
        
    }//GEN-LAST:event_SalvarNotaBtActionPerformed

    private void EditarNotaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarNotaBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarNotaBtActionPerformed

    private void ExcluirNotaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirNotaBtActionPerformed
        // TODO add your handling code here:
        //System.out.println("tamanho:"+ defaultTableModel.getRowCount());
    }//GEN-LAST:event_ExcluirNotaBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaView().setVisible(true);
            }
        });
    }
    
    public void setNomeDisciplina(String nome)
    {
        DisciplinaLb.setText(nome);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisciplinaLb;
    private javax.swing.JButton EditarNotaBt;
    private javax.swing.JButton ExcluirNotaBt;
    private javax.swing.JTable NotasTb;
    private javax.swing.JButton NovaNotaBt;
    private javax.swing.JButton SalvarNotaBt;
    private javax.swing.JButton VoltarBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
